name: Push PR

on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"  
  pull_request:
    branches:
      - main
      - "release/**"    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: npm test